### ISSUE TITLE
Support for sampling?

### ISSUE THREAD

**Issue by clauswilke** [DavisVaughan/strapgod#2]
I have been thinking that it would be nice to have the equivalent to `bootstrapify()` for sampling. This would work like `dplyr::sample_n()` but with two modifications:

1. Take a `times` argument for repeated sampling, just like `bootstrapify()`.
2. Set up virtual samples like `bootstrapify()`.

Not sure what to call the function. `samplefy()`? `samplify()`?

**Comment by DavisVaughan** [comment]
It would probably be pretty similar to `bootstrapify()` in terms of implementation, you just pass a few extra arguments through [here](https://github.com/DavisVaughan/strapgod/blob/master/R/bootstrapify.R#L102).

This seems useful, do you need it before the conf?

I like `samplify()` said like "samp-li-fy"

**Comment by clauswilke** [comment]
Yes, it would be helpful for me to have before the conf, though not essential if you're pressed for time.

I have implemented a workaround for now and have indicated the desired approach here:
https://github.com/clauswilke/ungeviz/blob/b28373140e9f50ffab75a2e08fcfbf586da71bcf/R/sampler.R#L107-L114

**Comment by DavisVaughan** [comment]
Could you take a look at 
https://github.com/DavisVaughan/strapgod/pull/3

and let me know what you think?

It basically makes the `bootstrapify()` implementation more general, as `samplify()` is just a more generic version of `bootstrapify()`. Hopefully I didn't break anything
